misc:
  exp_dir: kpconv_nuscenes_F+PP
  mode: train
  gpu_mode: True
  verbose: True
  verbose_freq: 150
  snapshot_freq: 1
  pretrain: ''
  pretrain_restart: False

model:
  num_layers: 4 
  in_points_dim: 3
  first_feats_dim: 128
  final_feats_dim: 32
  first_subsampling_dl: 0.3
  in_feats_dim: 1
  conv_radius: 4.25
  deform_radius: 5.0 
  num_kernel_points: 15
  KP_extent: 2.0
  KP_influence: linear
  aggregation_mode: sum 
  fixed_kernel_points: center
  use_batch_norm: True 
  batch_norm_momentum: 0.02
  deformable: False
  modulated: False 
  add_cross_score: True
  condition_feature: True

# overlap_attention_module:
#   gnn_feats_dim: 256 
#   dgcnn_k: 10
#   num_head: 4
#   nets: ['self','cross','self']

loss:
  pos_margin: 0.1
  neg_margin: 1.4
  finest_margin: 0.2
  log_scale: 48
  pos_radius: 0.21
  safe_radius: 0.75
  overlap_radius: 0.45
  matchability_radius: 0.3 
  w_circle_loss: 1.0
  w_overlap_loss: 1.0
  w_saliency_loss: 0.0
  max_points: 512

optimiser:
  optimizer: SGD
  max_epoch: 90
  lr: 0.1
  weight_decay: 0.0001
  momentum: 0.8
  scheduler: ExpLR
  scheduler_gamma: 0.99
  scheduler_freq: 1
  iter_size: 1

dataset:
  dataset: nuscenes_colocation
  benchmark: nucenes
  root: /mnt/disk/NUSCENES/nusc_kitti
  batch_size: 1 
  num_workers: 6
  augment_noise: 0.01
  augment_shift_range: 2.0 
  augment_scale_max: 1.2
  augment_scale_min: 0.8
  pair_min_dist: 5
  pair_max_dist: 50
  complement_pair_dist: 10
  num_complement_one_side: 4
  min_dist: 5
  max_dist: 60
  num_neighborhood: 6
  use_old_pose: False
  LoKITTI: False
  pos_weight: 0.7                     # weight of positive loss
  neg_weight: 0.7                     # weight of negative loss
  finest_weight: 1                    # weight of finest loss, set to 0 to numerically disable finest loss
  use_group_circle_loss: False        # enable loss design 'C'  (exclusive, enables circle loss and disables finest loss. If this is False, finest loss is enabled by default.)
  use_pair_group_positive_loss: True  # enable loss design 'PP' (use only a random pair inside a group for positive loss)
  block_finest_gradient: False        # enable loss design 'BF' (block gradient of finest loss on the finest feature)
